root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g ./cmd/duckbug/main.go && go build -o /opt/app/bin cmd/duckbug/*"
bin = "/opt/app/bin"
args_bin = ["--config", "configs/duckbug/config.json"]
delay = 500
exclude_dir = ["docs", "tmp", "var"]
