services:
  duckbug:
    container_name: duckbug
    image: ${REGISTRY}/duckbug:${IMAGE_TAG}
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      # Backend env
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.duckbug.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.duckbug.middlewares=secure-headers
      - traefik.http.routers.duckbug.entryPoints=https
      - traefik.http.routers.duckbug.tls=true
      - traefik.http.routers.duckbug.tls.certResolver=letsEncrypt
    restart: unless-stopped


networks:
  traefik-public:
    name: traefik-public
